services:
  auth-service:
    build: ./backend/auth-service
    container_name: ecommerce-auth
    ports:
      - "4001:4000"
    env_file:
      - ./backend/auth-service/.env

  notification-service:
    build: ./backend/notification-service
    container_name: ecommerce-notification
    ports:
      - "4002:3003"
    env_file:
      - ./backend/notification-service/.env
